# Generated by Django 3.0.5 on 2020-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0019_muser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehichle',
            name='shop_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
