# Generated by Django 3.0.5 on 2020-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0020_auto_20200718_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehichle',
            name='shop_name',
            field=models.CharField(default='No Shop available', max_length=200),
        ),
    ]
