# Generated by Django 3.1.2 on 2022-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0021_auto_20200724_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehichle',
            name='whatsapp_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
