# Generated by Django 3.1.2 on 2022-06-03 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0022_auto_20220603_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentVehichle',
            new_name='Workers',
        ),
        migrations.DeleteModel(
            name='Raja',
        ),
    ]
